version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: sample_db
      POSTGRES_PASSWORD: 123456
    ports:
      - '127.0.0.1:5432:5432'